repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: rubocop
        name: RuboCop
        entry: bin/rubocop
        language: system
        files: \.rb$
        args: [--autocorrect]

      - id: brakeman
        name: Brakeman Security Scan
        entry: bin/brakeman
        language: system
        files: \.rb$
        args: [--no-pager, --quiet]
        pass_filenames: false

